
# UK_Biobank
setValue("UK_Biobank", "Country", "UK")
setValue("UK_Biobank", "Sample_Size", "538050")
setValue("UK_Biobank", "Subject_Count", "500000")
setValue("UK_Biobank", "Study_Design", "Prospective study")
setValue("UK_Biobank", "Phenotypic_Variables", "")
setValue("UK_Biobank", "Phenotypic_Data_Type", "Health Record Data; Questionnaires; Physical Measures; Lifestyle")
setValue("UK_Biobank", "Molecular_Data_Type", "WGS; WES; Genotypes")
setValue("UK_Biobank", "Markerset", "Exome: IDT xGen Exome Research Panel v1.0")
setValue("UK_Biobank", "Disease_Focus", "General")
setValue("UK_Biobank","Patients_Age", "40-69")
setValue("UK_Biobank", "Ancestry", "White (95%); Other (5%)")
setValue("UK_Biobank", "Consent", "<a href='https://www.ukbiobank.ac.uk/gdpr/', target='_blank'>Consent for health-related research, for their health to be followed over many years through medical and other health-related records, as well as by being re-contacted by UK Biobank</a>")
setValue("UK_Biobank", "Accession", "<a href='http://www.ukbiobank.ac.uk/wp-content/uploads/2012/09/Access-Procedures-2011.pdf', target='_blank'>UK Biobank Access Procedures</a>")
setValue("UK_Biobank", "Link", "<a href='https://www.ukbiobank.ac.uk', target='_blank'>UK Biobank</a>")
setValue("UK_Biobank", "PubMedLink",  paste0(pubMed,"25826379[PMID]"))
setValue("UK_Biobank", "Notes", "<a href='http://biobank.ctsu.ox.ac.uk/crystal/browse.cgi', target='_blank'>UK Biobank Data Showcase</a>")

# UDN
setValue("UDN", "Country", "USA")
setValue("UDN", "Sample_Size", "")
setValue("UDN", "Subject_Count", "1042")
setValue("UDN", "Study_Design", "")
setValue("UDN", "Phenotypic_Variables", "3965")
setValue("UDN", "Phenotypic_Data_Type", "HPO terms")
setValue("UDN", "Molecular_Data_Type", "NGS")
setValue("UDN", "Markerset", "")
setValue("UDN", "Disease_Focus", "Undiagnosed Diseases")
setValue("UDN","Patients_Age", "0-")
setValue("UDN", "Ancestry", "White (81%); Asian (6%); American Indian or Alaska Native (<1%)'; Black or African American (5%); Native Hawaiian Pacific Islander (<1%); Other (8%)")
setValue("UDN", "Consent", "")
setValue("UDN", "Accession", "<a href='https://undiagnosed.hms.harvard.edu/research/', target='_blank'>UDN Research</a>")
setValue("UDN", "Link", "<a href='https://www.ukbiobank.ac.uk', target='_blank'>UDN Undiagnosed Disease Network</a>")
setValue("UDN", "PubMedLink",  paste0(pubMed,"26220576[PMID]"))
setValue("UDN", "Notes", "")


# FinnGen
setValue("FinnGen", "Country", "Finland")
setValue("FinnGen", "Sample_Size", "")
setValue("FinnGen", "Subject_Count", "299000")
setValue("FinnGen", "Study_Design", "")
setValue("FinnGen", "Phenotypic_Variables", "")
setValue("FinnGen", "Phenotypic_Data_Type", "")
setValue("FinnGen", "Molecular_Data_Type", "")
setValue("FinnGen", "Markerset", "")
setValue("FinnGen", "Disease_Focus", "General")
setValue("FinnGen","Patients_Age", "")
setValue("FinnGen", "Ancestry", "")
setValue("FinnGen", "Consent", "")
setValue("FinnGen", "Accession", "<a href='', target='_blank'></a>")
setValue("FinnGen", "Link", "<a href='https://www.finngen.fi/en/ ', target='_blank'>FinnGen</a>")
setValue("FinnGen", "PubMedLink",  paste0(pubMed,"[PMID]"))
setValue("FinnGen", "Notes", "")

# China Kadoorie
setValue("China_Kadoorie", "Country", "China")
setValue("China_Kadoorie", "Sample_Size", "")
setValue("China_Kadoorie", "Subject_Count", "510000")
setValue("China_Kadoorie", "Study_Design", "")
setValue("China_Kadoorie", "Phenotypic_Variables", "")
setValue("China_Kadoorie", "Phenotypic_Data_Type", "")
setValue("China_Kadoorie", "Molecular_Data_Type", "GWAS")
setValue("China_Kadoorie", "Markerset", "Common Chronic Diseases")
setValue("China_Kadoorie", "Disease_Focus", "")
setValue("China_Kadoorie","Patients_Age", "30-79")
setValue("China_Kadoorie", "Ancestry", "")
setValue("China_Kadoorie", "Consent", "")
setValue("China_Kadoorie", "Accession", "<a href='', target='_blank'></a>")
setValue("China_Kadoorie", "Link", "<a href='http://www.ckbiobank.org/site/', target='_blank'>China Kadoorie</a>")
setValue("China_Kadoorie", "PubMedLink",  paste0(pubMed,"[PMID]"))
setValue("China_Kadoorie", "Notes", "")


# Biobank Japan
setValue("Biobank_Japan", "Country", "Japan")
setValue("Biobank_Japan", "Sample_Size", "")
setValue("Biobank_Japan", "Subject_Count", "200000")
setValue("Biobank_Japan", "Study_Design", "")
setValue("Biobank_Japan", "Phenotypic_Variables", "")
setValue("Biobank_Japan", "Phenotypic_Data_Type", "")
setValue("Biobank_Japan", "Molecular_Data_Type", "")
setValue("Biobank_Japan", "Markerset", "")
setValue("Biobank_Japan", "Disease_Focus", "47 Common Diseases")
setValue("Biobank_Japan","Patients_Age", "")
setValue("Biobank_Japan", "Ancestry", "")
setValue("Biobank_Japan", "Consent", "")
setValue("Biobank_Japan", "Accession", "<a href='', target='_blank'></a>")
setValue("Biobank_Japan", "Link", "<a href='https://biobankjp.org/english/index.html', target='_blank'>Biobank Japan</a>")
setValue("Biobank_Japan", "PubMedLink",  paste0(pubMed,"[PMID]"))
setValue("Biobank_Japan", "Notes", "")

# H3_Africa
setValue("H3_Africa", "Country", "Africa")
setValue("H3_Africa", "Sample_Size", "")
setValue("H3_Africa", "Subject_Count", "")
setValue("H3_Africa", "Study_Design", "")
setValue("H3_Africa", "Phenotypic_Variables", "")
setValue("H3_Africa", "Phenotypic_Data_Type", "")
setValue("H3_Africa", "Molecular_Data_Type", "")
setValue("H3_Africa", "Markerset", "")
setValue("H3_Africa", "Disease_Focus", "")
setValue("H3_Africa","Patients_Age", "")
setValue("H3_Africa", "Ancestry", "")
setValue("H3_Africa", "Consent", "")
setValue("H3_Africa", "Accession", "<a href='', target='_blank'></a>")
setValue("H3_Africa", "Link", "<a href='', target='_blank'></a>")
setValue("H3_Africa", "PubMedLink",  paste0(pubMed,"[PMID]"))
setValue("H3_Africa", "Notes", "")

# Boston_Children_Hospital
setValue("Boston_Children_Biobank", "Country", "USA")
setValue("Boston_Children_Biobank", "Sample_Size", "")
setValue("Boston_Children_Biobank", "Subject_Count", "6000")
setValue("Boston_Children_Biobank", "Study_Design", "")
setValue("Boston_Children_Biobank", "Phenotypic_Variables", "")
setValue("Boston_Children_Biobank", "Phenotypic_Data_Type", "EHR; Surveys")
setValue("Boston_Children_Biobank", "Molecular_Data_Type", "WES")
setValue("Boston_Children_Biobank", "Markerset", "")
setValue("Boston_Children_Biobank", "Disease_Focus", "")
setValue("Boston_Children_Biobank","Patients_Age", "")
setValue("Boston_Children_Biobank", "Ancestry", "")
setValue("Boston_Children_Biobank", "Consent", "")
setValue("Boston_Children_Biobank", "Accession", "<a href='', target='_blank'></a>")
setValue("Boston_Children_Biobank", "Link", "<a href='http://biobank.childrens.harvard.edu', target='_blank'>Boston Children's Biobank</a>")
setValue("Boston_Children_Biobank", "PubMedLink",  paste0(pubMed,"29244735[PMID]"))
setValue("Boston_Children_Biobank", "Notes", "")

